name: sphinx-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dali,umap,h5] --extra-index-url https://developer.download.nvidia.com/compute/redist
          pip install -r docs/requirements.txt

      - name: Directly build sphinx
        run: |
          cd docs
          pip install -r requirements.txt
          make html

      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: build/html/
